language: java

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'

install: /bin/true

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN